spring.application.name=sotory
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

# Swagger
springdoc.swagger-ui.path=/index.html
springdoc.api-docs.path=/v3/api-docs
#server.servlet.context-path=/api

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
jwt.refresh-renew-threshold=${JWT_REFRESH_EXPIRATION_RENEW_THRESHOLD}

# FastAPI
fastapi.base.url = ${FASTAPI_URL}

#radis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# 날씨 API 
openweather.key=${OPEN_WEATHER_KEY}


# PostgreSQL ?? ??
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sotory}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ??

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.data.redis.host=localhost
#spring.data.redis.port=6379

fintech.api.key=${FINTECH_API_KEY}
fintech.institution.code=${FINTECH_INTSTITUTION_CODE}
fintech.app.no=${FINTECTH_APP_NO}
fintech.base.url=${FINTECH_BASE_URL}

fintech.key=${FINTECH_API_KEY}
fintech.regist=${FINTECH_REGISTER_URL}
fintech.user-key=${FINTECH_USER_KEY}

# ?? ?? ??? INFO? ????
logging.level.root=INFO

# Redis ?? ?? ??
logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=DEBUG

# JWT? ?? ?? ?? ?? ?
logging.level.com.sotory.auth=DEBUG
logging.level.com.sotory.auth.service=DEBUG

user.api_key=11b5541b-e433-447b-bf0d-56896d08ed49
weather.api.key=${OPEN_WEATHER_KEY}
