# TYPE  DATABASE        USER            ADDRESS                 METHOD

# local 접속 허용
local   all             all                                     trust

# 내부 네트워크 접속 허용
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# 외부 접속 허용
host    all             all             0.0.0.0/0               md5