# 베이스 이미지 설정
FROM python:3.11

# 기본 패키지 업데이트 및 OpenJDK 설치
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean

# JAVA_HOME 환경 변수 설정
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# 작업 디렉토리를 /app으로 설정
WORKDIR /app

# requirements.txt 복사 후 패키지 설치
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# app 폴더 내부 파일만 복사
COPY ./app /app
ENV PYTHONPATH=/app

# FastAPI 실행 (개발 모드)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
# CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:8000", "--workers", "4"]
